### PR TITLE
inspect: add empty auth conf as default

### LINKED ISSUE #2: Failing to pull images when they don't exists on the node
When the image is not present on the node the pull is failing:

```
# docker run --rm -ti --privileged -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock image-inspector:2.0.0-1 --chroot --image=docker.io/fedora:23 --scan-type=openscap --serve=0.0.0.0:8080
2016/05/10 16:52:05 Pulling image docker.io/fedora:23
2016/05/10 16:52:05 Error inspecting image: Unable to create docker container: no such image
```

cc @enoodle @moolitayer

This is a critical and urgent issue.

### PR DESCRIPTION
**Pull request by enoodle**
When no authentication configuration are given
make sure that a default empty one is returned.

Fixes #2

### CODE REVIEW

**Comment by simon3z** [comment]
@enoodle can we add tests for this?

**Comment by enoodle** [comment]
@simon3z I added a test

File: pkg/inspector/image-inspector_test.go [hunk 1]
```diff
@@ -91,18 +93,19 @@ func TestGetAuthConfigs(t *testing.T) {
...
 		if !v.shouldFail {
-			var expectedLength int = len(v.opts.DockerCfg.Values)
+			var expectedLength int = len(v.opts.DockerCfg.Values) + 1
 			if len(v.opts.Username) > 0 {
-				expectedLength = expectedLength + 1
+				expectedLength = 1
 			}
 			if err != nil {
-				t.Errorf("%s expected to validate but received %v", k, err)
+				t.Errorf("%s expected to succeed but received %v", k, err)
```
Comment (enoodle) [inline pkg/inspector/image-inspector_test.go]: thats a typo fix to make the test fail message more clear

**Comment by simon3z** [comment]
@pweil- can you review? Thanks.

**Comment by pweil-** [comment]
LGTM
